modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/LMokahel/No-More-Overlays/issues"
license = "All Rights Reserved"

[[mods]]
modId = "nomoreoverlays"
version = "${version}"
displayName = "No More Overlays"
authors = "DontNag"
description = '''
Allows the user to toggle all of minecraft's screen effects.
'''
#logoFile = ""
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.nomoreoverlays]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nomoreoverlays]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.3)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nomoreoverlays]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.14,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.nomoreoverlays]]
modId = "cloth_config"
mandatory = true
versionRange = "[12.0.110,)"
ordering = "AFTER"
side = "CLIENT"
