modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/LMokahel/No-More-Overlays/issues"
license = "All Rights Reserved"

[[mods]]
modId = "nomoreoverlays"
version = "${version}"
displayName = "No More Overlays"
authors = "DontNag"
description = "Minecraft mod that allows the user to toggle all of Minecraft's screen effects."

[[dependencies.nomoreoverlays]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nomoreoverlays]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nomoreoverlays]]
modId = "cloth_config"
mandatory = true
versionRange = "[13.0.112,)"
ordering = "AFTER"
side = "CLIENT"
