modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/LMokahel/No-More-Overlays/issues"
license = "All Rights Reserved"
clientSideOnly = true

[[mods]]
modId = "nomoreoverlays"
version = "${version}"
displayName = "${mod_name}"
authors = "DontNag"
description = '''Minecraft mod that allows the user to toggle all of Minecraft's screen effects.'''
logoFile = "icon.png"

[[dependencies.nomoreoverlays]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nomoreoverlays]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "nomoreoverlays.mixins.json"
